### ISSUE TITLE
Crear contenido de la sección HOME

### ISSUE THREAD

**Issue by jrodriguez2076** [aniitasmith/poche#3]
- Leer los datos de los locales desde un archivo local `ratings.json`, que tendrá un listado de los locales, junto con sus respectivos ratings ([archivo aqui](https://github.com/jrodriguez2076/poche-api/blob/main/ratings.json), descargar y agregar al directorio del proyecto, o copiar y pegar los datos en un archivo nuevo)
- Crear componente `<Card/>`, que mostrará información respecto al local:
![image](https://user-images.githubusercontent.com/36515945/188332742-9b54da1b-69d7-48f9-adf1-dab55557ae6c.png)
  - Deberá mostrar el rating de las cards dentro de un icono (El ícono de estrella es referencia, se puede reemplazar por cualquier otro icono)
![image](https://user-images.githubusercontent.com/36515945/188332998-d8438bb7-647a-47c0-be0a-127a8aa1ec7b.png)

- Agregar todos los locales a la página HOME, reutilizando el componente `<Card/>` recién creado. Agregar todos en una misma lista. esta lista deberá estar entre los Componentes Header y Footer creados anteriormente.

IMPORTANTE: si la lista de locales llegase a ser muy larga, el FOOTER no puede desaparecer del final de la pantalla. SIEMPRE debe estar fijo en el final, y la lista de locales deberá ser scrollable DENTRO del componente HOME.

**Comment by aniitasmith** [comment]
![Image](https://user-images.githubusercontent.com/66226368/189252643-c6e22e73-f9c6-42f1-8a3f-597ba6f4294b.png)

no puedo ver el archivo
